import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    // Navbar
    'nav.home': 'Trang Chủ',
    'nav.collections': 'Bộ Sưu Tập',
    'nav.about': 'Về Chúng Tôi',
    'nav.contact': 'Liên Hệ',
    'nav.admin': 'Quản Trị',
    'nav.search': 'Tìm kiếm sản phẩm...',
    'nav.cart': 'Giỏ Hàng',
    'nav.account': 'Tài Khoản',
    
    // HomeView
    'home.promo.exclusive': 'Khuyến Mãi Độc Quyền',
    'home.new.subtitle': 'Mới Nhất',
    'home.new.title': 'Sản Phẩm Mới',
    'home.viewAll': 'Xem Tất Cả',
    'home.best.subtitle': 'Yêu Thích Nhất',
    'home.best.title': 'Sản Phẩm Bán Chạy',
    'home.story.subtitle': 'Về Chúng Tôi',
    'home.story.title': 'Hành Trình Tìm Kiếm Vẻ Đẹp Vĩnh Cửu',
    'home.story.p1': 'Khởi nguồn từ niềm đam mê mãnh liệt với những viên ngọc quý từ vùng đất Myanmar huyền bí, Phỉ Thúy Lê Công đã trải qua hơn hai thập kỷ để xây dựng nên một thương hiệu uy tín, nơi mỗi sản phẩm đều là một kiệt tác nghệ thuật.',
    'home.story.p2': 'Chúng tôi không chỉ bán trang sức, chúng tôi chia sẻ những câu chuyện về văn hóa, tâm linh và sự bình an mà ngọc phỉ thúy mang lại cho chủ nhân của nó.',
    'home.story.btn': 'Khám Phá Thêm',
    'home.blog.subtitle': 'Kiến Thức Ngọc',
    'home.blog.title': 'Blog & Tin Tức',
    'home.blog.readMore': 'Đọc Tiếp',
    'home.sub.subtitle': 'Tham Gia Cùng Chúng Tôi',
    'home.sub.title': 'Nhận Ưu Đãi Độc Quyền',
    'home.sub.desc': 'Đăng ký bản tin để nhận thông tin về bộ sưu tập mới nhất và các kiến thức chuyên sâu về ngọc phỉ thúy.',
    'home.sub.placeholder': 'Địa chỉ email của bạn',
    'home.sub.btn': 'Đăng Ký Ngay',
    'home.sub.note': 'Chúng tôi tôn trọng quyền riêng tư của bạn. Hủy đăng ký bất cứ lúc nào.',

    // CollectionsView
    'col.title': 'Bộ Sưu Tập',
    'col.desc': 'Khám phá những tuyệt tác ngọc phỉ thúy được tuyển chọn kỹ lưỡng, mang vẻ đẹp vượt thời gian và giá trị phong thủy sâu sắc.',
    'col.page.title': 'Bộ Sưu Tập Phỉ Thúy Tuyệt Mỹ',
    'col.page.desc': 'Ngọc Phỉ Thúy Myanmar Loại A được tuyển chọn thủ công. Mỗi món đồ là duy nhất về độ trong suốt, kết cấu và sự biến đổi màu sắc tự nhiên.',
    'col.searchResult': 'Kết quả tìm kiếm cho: ',
    'col.filter.category': 'Loại Sản Phẩm',
    'col.filter.collection': 'Dòng Sản Phẩm',
    'col.filter.price': 'Khoảng Giá',
    'col.filter.all': 'Tất Cả',
    'col.filter.bracelet': 'Vòng Tay',
    'col.filter.pendant': 'Mặt Dây Chuyền',
    'col.filter.ring': 'Nhẫn',
    'col.filter.earring': 'Bông Tai',
    'col.sort.featured': 'Sắp xếp: Nổi bật',
    'col.sort.newest': 'Mới Nhất',
    'col.sort.priceAsc': 'Giá: Thấp đến Cao',
    'col.sort.priceDesc': 'Giá: Cao đến Thấp',
    'col.sort.nameAsc': 'Tên: A-Z',
    'col.sort.nameDesc': 'Tên: Z-A',
    'col.show': 'Hiển thị: ',
    'col.showing': 'Đang hiển thị ',
    'col.of': ' trên ',
    'col.items': ' kiệt tác',
    'col.emptyFilter': 'Không tìm thấy sản phẩm nào phù hợp với bộ lọc của bạn.',
    'col.empty': 'Không tìm thấy sản phẩm nào.',

    // ProductDetailView
    'prod.back': 'Quay Lại',
    'prod.addCart': 'Thêm Vào Giỏ',
    'prod.buyNow': 'Mua Ngay',
    'prod.desc.prefix': 'Kiệt tác tinh xảo này được chế tác từ ngọc phỉ thúy Myanmar tự nhiên, nổi tiếng với màu sắc rực rỡ và độ trong suốt đặc biệt. Mỗi viên đá là duy nhất, mang trong mình những hoa văn và năng lượng tự nhiên riêng biệt.',
    'prod.category': 'Loại Sản Phẩm',
    'prod.collection': 'Dòng Sản Phẩm',
    'prod.shipping.free': 'Giao Hàng Hỏa Tốc Miễn Phí',
    'prod.guarantee': 'Đảm Bảo Chính Hãng',
    'prod.tab.details': 'Chi Tiết & Bảo Quản',
    'prod.tab.shipping': 'Giao Hàng & Trả Hàng',
    'prod.tab.reviews': 'Đánh Giá Khách Hàng',
    'prod.details.desc.title': 'Mô Tả Sản Phẩm',
    'prod.details.desc.content1': 'Sản phẩm ',
    'prod.details.desc.content2': ' của chúng tôi là minh chứng cho vẻ đẹp của ngọc phỉ thúy tự nhiên. Được lấy từ những mỏ ngọc huyền thoại của Myanmar, món đồ này đã được các nghệ nhân bậc thầy đánh bóng thủ công để làm lộ ra vẻ rạng rỡ bên trong. Ngọc không chỉ là một viên đá; nó là biểu tượng của sự bảo vệ, thịnh vượng và bình an.',
    'prod.details.care.title': 'Hướng Dẫn Bảo Quản',
    'prod.details.care.1': 'Lau sạch bằng vải mềm, ẩm sau mỗi lần đeo.',
    'prod.details.care.2': 'Tránh tiếp xúc với hóa chất mạnh hoặc nước hoa.',
    'prod.details.care.3': 'Bảo quản trong hộp lót nhung đi kèm để tránh trầy xước.',
    'prod.details.care.4': 'Tránh thay đổi nhiệt độ đột ngột hoặc nhiệt độ cao.',
    'prod.shipping.policy.title': 'Chính Sách Giao Hàng',
    'prod.shipping.policy.1': 'Giao hàng hỏa tốc miễn phí cho mọi đơn hàng trên toàn quốc.',
    'prod.shipping.policy.2': 'Thời gian giao hàng dự kiến: 1-3 ngày làm việc đối với khu vực nội thành, 3-5 ngày đối với các tỉnh thành khác.',
    'prod.shipping.policy.3': 'Tất cả các kiện hàng đều được đóng gói cẩn thận, niêm phong và bảo hiểm 100% giá trị.',
    'prod.shipping.policy.4': 'Quý khách được quyền kiểm tra hàng trước khi thanh toán.',
    'prod.return.policy.title': 'Chính Sách Trả Hàng & Hoàn Tiền',
    'prod.return.policy.1': 'Hỗ trợ đổi trả miễn phí trong vòng 7 ngày kể từ ngày nhận hàng nếu có lỗi từ nhà sản xuất.',
    'prod.return.policy.2': 'Sản phẩm đổi trả phải còn nguyên vẹn, chưa qua sử dụng, đầy đủ hộp, phụ kiện và giấy tờ đi kèm.',
    'prod.return.policy.3': 'Hoàn tiền 100% nếu phát hiện sản phẩm không đúng cam kết chất lượng.',
    'prod.return.policy.4': 'Quy trình hoàn tiền sẽ được xử lý trong vòng 3-5 ngày làm việc sau khi chúng tôi nhận lại sản phẩm.',
    'prod.related': 'Có Thể Bạn Cũng Thích',
    'prod.badge.new': 'Mới',
    'prod.badge.premium': 'Cao Cấp',
    'prod.details.material': 'Chất liệu:',
    'prod.details.origin': 'Nguồn gốc:',
    'prod.details.color': 'Màu sắc:',
    'prod.details.size': 'Kích thước:',
    'prod.details.cert': 'Chứng nhận:',
    'prod.care.title': 'Hướng Dẫn Bảo Quản:',
    'prod.care.1': 'Tránh va đập mạnh hoặc tiếp xúc với hóa chất.',
    'prod.care.2': 'Làm sạch bằng vải mềm và nước ấm.',
    'prod.care.3': 'Bảo quản trong hộp lót nhung khi không sử dụng.',
    'prod.ship.title': 'Chính Sách Giao Hàng:',
    'prod.ship.1': 'Miễn phí giao hàng toàn quốc cho đơn hàng từ 5,000,000đ.',
    'prod.ship.2': 'Thời gian giao hàng dự kiến: 2-4 ngày làm việc.',
    'prod.ship.3': 'Đóng gói an toàn, bảo mật, kèm hộp quà tặng cao cấp.',
    'prod.return.title': 'Chính Sách Trả Hàng:',
    'prod.return.1': 'Đổi trả miễn phí trong vòng 7 ngày nếu có lỗi từ nhà sản xuất.',
    'prod.return.2': 'Sản phẩm đổi trả phải còn nguyên vẹn, đầy đủ giấy tờ và hộp đi kèm.',
    'prod.return.3': 'Hoàn tiền 100% nếu phát hiện ngọc giả hoặc không đúng cam kết.',

    // CartView
    'cart.empty.title': 'Giỏ hàng của bạn đang trống',
    'cart.empty.desc': 'Khám phá bộ sưu tập tuyệt mỹ của chúng tôi và tìm món đồ hoàn hảo cho bạn.',
    'cart.empty.btn': 'Khám Phá Bộ Sưu Tập',
    'cart.title': 'Giỏ Hàng',
    'cart.continue': 'Tiếp Tục Mua Sắm',
    'cart.summary.title': 'Tóm Tắt Đơn Hàng',
    'cart.voucher.label': 'Mã Giảm Giá',
    'cart.voucher.placeholder': 'Ví dụ: DISCOUNT10',
    'cart.voucher.apply': 'Áp dụng',
    'cart.voucher.cancel': 'Hủy',
    'cart.voucher.empty': 'Vui lòng nhập mã giảm giá',
    'cart.voucher.invalid': 'Mã giảm giá không hợp lệ hoặc đã hết hạn',
    'cart.voucher.error': 'Lỗi khi kiểm tra mã giảm giá',
    'cart.voucher.success': 'Đã áp dụng mã giảm giá thành công!',
    'cart.summary.subtotal': 'Tạm tính',
    'cart.summary.discount': 'Giảm giá',
    'cart.summary.shipping': 'Phí vận chuyển',
    'cart.summary.free': 'MIỄN PHÍ',
    'cart.summary.tax': 'Thuế ước tính',
    'cart.summary.taxCalc': 'Tính khi thanh toán',
    'cart.summary.total': 'Tổng cộng',
    'cart.checkout': 'Tiến Hành Thanh Toán',

    // AuthView
    'auth.login.title': 'Chào Mừng Trở Lại',
    'auth.login.desc': 'Đăng nhập để truy cập bộ sưu tập của bạn',
    'auth.register.title': 'Tham Gia Phỉ Thúy Lê Công',
    'auth.register.desc': 'Tạo tài khoản để nhận các ưu đãi độc quyền',
    'auth.email': 'Địa chỉ Email',
    'auth.password': 'Mật Khẩu',
    'auth.forgot': 'Quên?',
    'auth.confirmPassword': 'Xác Nhận Mật Khẩu',
    'auth.login.btn': 'Đăng Nhập',
    'auth.register.btn': 'Tạo Tài Khoản',
    'auth.loading': 'Đang xử lý...',
    'auth.noAccount': 'Chưa có tài khoản?',
    'auth.hasAccount': 'Đã có tài khoản?',
    'auth.signup': 'Đăng Ký',
    'auth.error.mismatch': 'Mật khẩu xác nhận không khớp.',

    // ProfileView
    'profile.tab.overview': 'Tổng Quan',
    'profile.tab.admin': 'Quản Trị Viên',
    'profile.tab.profile': 'Thông Tin Cá Nhân',
    'profile.tab.orders': 'Lịch Sử Đơn Hàng',
    'profile.logout': 'Đăng Xuất',
    'profile.welcome': 'Chào mừng trở lại, ',
    'profile.overview.totalOrders': 'Tổng Đơn Hàng',
    'profile.overview.totalSpent': 'Giá Trị Bộ Sưu Tập',
    'profile.overview.tier': 'Hạng Thành Viên',
    'profile.overview.tier.elite': 'Jade Elite',
    'profile.overview.tier.member': 'Thành Viên',
    'profile.form.email': 'Email (Không thể thay đổi)',
    'profile.form.name': 'Họ và Tên',
    'profile.form.phone': 'Số Điện Thoại',
    'profile.form.address': 'Địa Chỉ Giao Hàng',
    'profile.form.save': 'Lưu Thay Đổi',
    'profile.form.saving': 'Đang Lưu...',
    'profile.form.success': 'Cập nhật thông tin thành công!',
    'profile.form.error': 'Lỗi khi cập nhật thông tin.',
    'profile.form.connError': 'Lỗi kết nối.',
    'profile.orders.loading': 'Đang tải đơn hàng...',
    'profile.orders.empty': 'Bạn chưa có đơn hàng nào.',
    'profile.orders.id': 'Mã Đơn Hàng',
    'profile.orders.date': 'Ngày',
    'profile.orders.status': 'Trạng Thái',
    'profile.orders.total': 'Tổng Cộng',

    // CheckoutView
    'checkout.error': 'Có lỗi xảy ra khi đặt hàng. Vui lòng thử lại.',
    'checkout.success.title': 'Đặt Hàng Thành Công!',
    'checkout.success.desc': 'Cảm ơn bạn đã mua sắm tại Phỉ thúy Lê Công. Chúng tôi đã nhận được thông tin thanh toán và sẽ xử lý đơn hàng của bạn trong thời gian sớm nhất.',
    'checkout.success.home': 'Trở Về Trang Chủ',
    'checkout.title': 'Thanh Toán',
    'checkout.bank.title': 'Thông Tin Chuyển Khoản',
    'checkout.bank.desc': 'Vui lòng chuyển khoản với nội dung là số điện thoại của bạn hoặc mã đơn hàng.',
    'checkout.bank.name': 'Ngân hàng',
    'checkout.bank.owner': 'Chủ tài khoản',
    'checkout.bank.number': 'Số tài khoản',
    'checkout.bank.amount': 'Số tiền',
    'checkout.bank.content': 'Nội dung',
    'checkout.qr.title': 'Quét Mã QR',
    'checkout.qr.desc': 'Mở ứng dụng ngân hàng và quét mã QR để thanh toán nhanh',
    'checkout.upload.title': 'Xác Nhận Thanh Toán',
    'checkout.upload.desc': 'Sau khi chuyển khoản thành công, vui lòng tải lên hình ảnh biên lai để chúng tôi xác nhận đơn hàng nhanh chóng hơn.',
    'checkout.upload.change': 'Nhấn để thay đổi',
    'checkout.upload.btn': 'Tải lên biên lai',
    'checkout.upload.support': 'Hỗ trợ JPG, PNG (Tối đa 5MB)',
    'checkout.submit.processing': 'Đang xử lý...',
    'checkout.submit.done': 'Hoàn Tất Đặt Hàng',
    'checkout.details.title': 'Thông Tin Giao Hàng',
    'checkout.details.name': 'Họ và Tên *',
    'checkout.details.name.placeholder': 'Nhập họ và tên của bạn',
    'checkout.details.phone': 'Số Điện Thoại *',
    'checkout.details.phone.placeholder': 'Nhập số điện thoại của bạn',
    'checkout.details.email': 'Email (Không bắt buộc)',
    'checkout.details.email.placeholder': 'Nhập email của bạn',
    'checkout.details.address': 'Địa Chỉ Giao Hàng *',
    'checkout.details.address.placeholder': 'Nhập địa chỉ giao hàng chi tiết',
    'checkout.details.notes': 'Ghi Chú Đơn Hàng',
    'checkout.details.notes.placeholder': 'Nhập ghi chú hoặc yêu cầu đặc biệt cho đơn hàng của bạn',
    'checkout.details.proceed': 'Tiến Hành Thanh Toán',

    // Footer
    'footer.desc': 'Nơi tôn vinh vẻ đẹp vĩnh cửu của ngọc phỉ thúy Myanmar. Mỗi sản phẩm là một kiệt tác nghệ thuật mang đậm giá trị văn hóa và tâm linh.',
    'footer.links': 'Liên Kết Nhanh',
    'footer.support': 'Hỗ Trợ Khách Hàng',
    'footer.support.guide': 'Hướng Dẫn Mua Hàng',
    'footer.support.size': 'Chính Sách Đổi Trả',
    'footer.support.faq': 'Câu Hỏi Thường Gặp',
    'footer.contact': 'Liên Hệ',
    'footer.rights': 'Bản quyền thuộc về Phỉ Thúy Lê Công.',

    // General
    'btn.buyNow': 'Mua Ngay',
    'btn.discover': 'Khám Phá',
    'btn.learnMore': 'Tìm Hiểu Thêm',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.collections': 'Collections',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.search': 'Search products...',
    'nav.cart': 'Cart',
    'nav.account': 'Account',

    // HomeView
    'home.promo.exclusive': 'Exclusive Promotion',
    'home.new.subtitle': 'New Arrivals',
    'home.new.title': 'Latest Products',
    'home.viewAll': 'View All',
    'home.best.subtitle': 'Most Loved',
    'home.best.title': 'Best Sellers',
    'home.story.subtitle': 'About Us',
    'home.story.title': 'The Journey to Eternal Beauty',
    'home.story.p1': 'Originating from a fierce passion for precious gems from the mystical land of Myanmar, Le Cong Jade has spent over two decades building a reputable brand where every product is an artistic masterpiece.',
    'home.story.p2': 'We do not just sell jewelry, we share stories of culture, spirituality, and the peace that jade brings to its owner.',
    'home.story.btn': 'Explore More',
    'home.blog.subtitle': 'Jade Knowledge',
    'home.blog.title': 'Blog & News',
    'home.blog.readMore': 'Read More',
    'home.sub.subtitle': 'Join Us',
    'home.sub.title': 'Get Exclusive Offers',
    'home.sub.desc': 'Subscribe to our newsletter to receive information about the latest collections and in-depth knowledge about jade.',
    'home.sub.placeholder': 'Your email address',
    'home.sub.btn': 'Subscribe Now',
    'home.sub.note': 'We respect your privacy. Unsubscribe at any time.',

    // CollectionsView
    'col.title': 'Collections',
    'col.desc': 'Discover carefully curated jade masterpieces, bearing timeless beauty and profound feng shui values.',
    'col.page.title': 'Exquisite Jade Collection',
    'col.page.desc': 'Hand-selected Grade A Myanmar Jade. Each piece is unique in its transparency, texture, and natural color variations.',
    'col.searchResult': 'Search results for: ',
    'col.filter.category': 'Category',
    'col.filter.collection': 'Collection',
    'col.filter.price': 'Price Range',
    'col.filter.all': 'All',
    'col.filter.bracelet': 'Bracelet',
    'col.filter.pendant': 'Pendant',
    'col.filter.ring': 'Ring',
    'col.filter.earring': 'Earring',
    'col.sort.featured': 'Sort by: Featured',
    'col.sort.newest': 'Newest',
    'col.sort.priceAsc': 'Price: Low to High',
    'col.sort.priceDesc': 'Price: High to Low',
    'col.sort.nameAsc': 'Name: A-Z',
    'col.sort.nameDesc': 'Name: Z-A',
    'col.show': 'Show: ',
    'col.showing': 'Showing ',
    'col.of': ' of ',
    'col.items': ' masterpieces',
    'col.emptyFilter': 'No products found matching your filters.',
    'col.empty': 'No products found.',

    // ProductDetailView
    'prod.back': 'Back',
    'prod.addCart': 'Add to Cart',
    'prod.buyNow': 'Buy Now',
    'prod.desc.prefix': 'This exquisite masterpiece is crafted from natural Myanmar jade, renowned for its vibrant color and exceptional transparency. Each stone is unique, carrying its own distinct natural patterns and energy.',
    'prod.category': 'Category',
    'prod.collection': 'Collection',
    'prod.shipping.free': 'Free Express Shipping',
    'prod.guarantee': 'Authenticity Guaranteed',
    'prod.tab.details': 'Details & Care',
    'prod.tab.shipping': 'Shipping & Returns',
    'prod.tab.reviews': 'Customer Reviews',
    'prod.details.desc.title': 'Product Description',
    'prod.details.desc.content1': 'Our ',
    'prod.details.desc.content2': ' is a testament to the beauty of natural jade. Sourced from the legendary mines of Myanmar, this piece has been hand-polished by master artisans to reveal its inner radiance. Jade is not just a stone; it is a symbol of protection, prosperity, and peace.',
    'prod.details.care.title': 'Care Instructions',
    'prod.details.care.1': 'Wipe clean with a soft, damp cloth after each wear.',
    'prod.details.care.2': 'Avoid contact with harsh chemicals or perfumes.',
    'prod.details.care.3': 'Store in the provided velvet-lined box to prevent scratches.',
    'prod.details.care.4': 'Avoid sudden temperature changes or high heat.',
    'prod.shipping.policy.title': 'Shipping Policy',
    'prod.shipping.policy.1': 'Free express shipping for all orders nationwide.',
    'prod.shipping.policy.2': 'Estimated delivery time: 1-3 business days for urban areas, 3-5 days for other provinces.',
    'prod.shipping.policy.3': 'All packages are carefully packed, sealed, and 100% insured.',
    'prod.shipping.policy.4': 'Customers have the right to inspect the goods before payment.',
    'prod.return.policy.title': 'Return & Refund Policy',
    'prod.return.policy.1': 'Free returns within 7 days of receipt for manufacturer defects.',
    'prod.return.policy.2': 'Returned products must be intact, unused, with full box, accessories, and accompanying papers.',
    'prod.return.policy.3': '100% refund if the product is found to be not as promised.',
    'prod.return.policy.4': 'The refund process will be handled within 3-5 business days after we receive the product back.',
    'prod.related': 'You May Also Like',
    'prod.badge.new': 'New',
    'prod.badge.premium': 'Premium',
    'prod.details.material': 'Material:',
    'prod.details.origin': 'Origin:',
    'prod.details.color': 'Color:',
    'prod.details.size': 'Size:',
    'prod.details.cert': 'Certification:',
    'prod.care.title': 'Care Instructions:',
    'prod.care.1': 'Avoid strong impacts or contact with chemicals.',
    'prod.care.2': 'Clean with a soft cloth and warm water.',
    'prod.care.3': 'Store in a velvet-lined box when not in use.',
    'prod.ship.title': 'Shipping Policy:',
    'prod.ship.1': 'Free nationwide shipping for orders over 5,000,000 VND.',
    'prod.ship.2': 'Estimated delivery time: 2-4 business days.',
    'prod.ship.3': 'Safe, secure packaging, with premium gift box.',
    'prod.return.title': 'Return Policy:',
    'prod.return.1': 'Free returns within 7 days for manufacturer defects.',
    'prod.return.2': 'Returned products must be intact, with all papers and accompanying boxes.',
    'prod.return.3': '100% refund if fake jade is detected or not as promised.',

    // CartView
    'cart.empty.title': 'Your cart is empty',
    'cart.empty.desc': 'Discover our exquisite collection and find the perfect piece for you.',
    'cart.empty.btn': 'Discover Collection',
    'cart.title': 'Shopping Cart',
    'cart.continue': 'Continue Shopping',
    'cart.summary.title': 'Order Summary',
    'cart.voucher.label': 'Discount Code',
    'cart.voucher.placeholder': 'Example: DISCOUNT10',
    'cart.voucher.apply': 'Apply',
    'cart.voucher.cancel': 'Cancel',
    'cart.voucher.empty': 'Please enter a discount code',
    'cart.voucher.invalid': 'Invalid or expired discount code',
    'cart.voucher.error': 'Error checking discount code',
    'cart.voucher.success': 'Discount code applied successfully!',
    'cart.summary.subtotal': 'Subtotal',
    'cart.summary.discount': 'Discount',
    'cart.summary.shipping': 'Shipping',
    'cart.summary.free': 'FREE',
    'cart.summary.tax': 'Estimated Tax',
    'cart.summary.taxCalc': 'Calculated at checkout',
    'cart.summary.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',

    // AuthView
    'auth.login.title': 'Welcome Back',
    'auth.login.desc': 'Log in to access your collection',
    'auth.register.title': 'Join Le Cong Jade',
    'auth.register.desc': 'Create an account to receive exclusive offers',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.forgot': 'Forgot?',
    'auth.confirmPassword': 'Confirm Password',
    'auth.login.btn': 'Log In',
    'auth.register.btn': 'Create Account',
    'auth.loading': 'Processing...',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.signup': 'Sign Up',
    'auth.error.mismatch': 'Passwords do not match.',

    // ProfileView
    'profile.tab.overview': 'Overview',
    'profile.tab.admin': 'Admin Panel',
    'profile.tab.profile': 'Personal Info',
    'profile.tab.orders': 'Order History',
    'profile.logout': 'Log Out',
    'profile.welcome': 'Welcome back, ',
    'profile.overview.totalOrders': 'Total Orders',
    'profile.overview.totalSpent': 'Collection Value',
    'profile.overview.tier': 'Membership Tier',
    'profile.overview.tier.elite': 'Jade Elite',
    'profile.overview.tier.member': 'Member',
    'profile.form.email': 'Email (Cannot be changed)',
    'profile.form.name': 'Full Name',
    'profile.form.phone': 'Phone Number',
    'profile.form.address': 'Shipping Address',
    'profile.form.save': 'Save Changes',
    'profile.form.saving': 'Saving...',
    'profile.form.success': 'Profile updated successfully!',
    'profile.form.error': 'Error updating profile.',
    'profile.form.connError': 'Connection error.',
    'profile.orders.loading': 'Loading orders...',
    'profile.orders.empty': 'You have no orders yet.',
    'profile.orders.id': 'Order ID',
    'profile.orders.date': 'Date',
    'profile.orders.status': 'Status',
    'profile.orders.total': 'Total',

    // CheckoutView
    'checkout.error': 'An error occurred while placing the order. Please try again.',
    'checkout.success.title': 'Order Placed Successfully!',
    'checkout.success.desc': 'Thank you for shopping at Le Cong Jade. We have received your payment information and will process your order as soon as possible.',
    'checkout.success.home': 'Return to Home',
    'checkout.title': 'Checkout',
    'checkout.bank.title': 'Bank Transfer Information',
    'checkout.bank.desc': 'Please transfer with your phone number or order code as the description.',
    'checkout.bank.name': 'Bank',
    'checkout.bank.owner': 'Account Holder',
    'checkout.bank.number': 'Account Number',
    'checkout.bank.amount': 'Amount',
    'checkout.bank.content': 'Description',
    'checkout.qr.title': 'Scan QR Code',
    'checkout.qr.desc': 'Open your banking app and scan the QR code for quick payment',
    'checkout.upload.title': 'Confirm Payment',
    'checkout.upload.desc': 'After successful transfer, please upload a picture of the receipt so we can confirm your order faster.',
    'checkout.upload.change': 'Click to change',
    'checkout.upload.btn': 'Upload receipt',
    'checkout.upload.support': 'Supports JPG, PNG (Max 5MB)',
    'checkout.submit.processing': 'Processing...',
    'checkout.submit.done': 'Complete Order',
    'checkout.details.title': 'Delivery Information',
    'checkout.details.name': 'Full Name *',
    'checkout.details.name.placeholder': 'Enter your full name',
    'checkout.details.phone': 'Phone Number *',
    'checkout.details.phone.placeholder': 'Enter your phone number',
    'checkout.details.email': 'Email (Optional)',
    'checkout.details.email.placeholder': 'Enter your email',
    'checkout.details.address': 'Shipping Address *',
    'checkout.details.address.placeholder': 'Enter your full shipping address',
    'checkout.details.notes': 'Order Notes',
    'checkout.details.notes.placeholder': 'Enter any special requests or notes for your order',
    'checkout.details.proceed': 'Proceed to Payment',

    // Footer
    'footer.desc': 'Honoring the eternal beauty of Myanmar jade. Each product is an artistic masterpiece rich in cultural and spiritual value.',
    'footer.links': 'Quick Links',
    'footer.support': 'Customer Support',
    'footer.support.guide': 'Shopping Guide',
    'footer.support.size': 'Return Policy',
    'footer.support.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.rights': 'Copyright by Le Cong Jade.',

    // General
    'btn.buyNow': 'Buy Now',
    'btn.discover': 'Discover',
    'btn.learnMore': 'Learn More',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('vi');

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
